name: veETH-DAI with RariFuse
on:
  pull_request:
    paths:
      - "test/veth/vesper-earn-rari-fuse.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/compound/CompoundStrategy.sol"
      - "contracts/strategies/rari-fuse/RariFuseStrategy.sol"
      - "contracts/strategies/rari-fuse/earn/EarnRariFuseStrategy.sol"
      - "contracts/strategies/rari-fuse/earn/EarnRariFuseStrategyETH.sol"

jobs:
  veth-earn-rari-fuse:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running vETH-DAI with RariFuse
        run: npm test "test/veth/vesper-earn-rari-fuse.js"
