name: veETH-DAI with Yearn
on:
  pull_request:
    paths:
      - "test/veth/vesper-earn-yearn.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/yearn/YearnStrategy.sol"
      - "contracts/strategies/yearn/earn/EarnYearnStrategy.sol"
      - "contracts/strategies/yearn/earn/EarnYearnStrategyETH.sol"

jobs:
  veth-earn-yearn:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running vETH-DAI with Yearn
        run: npm test "test/veth/vesper-earn-yearn.js"
