name: veETH-DAI with Aave
on:
  pull_request:
    paths:
      - "test/veth/vesper-earn-aave.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/aave/AaveCore.sol"
      - "contracts/strategies/aave/AaveStrategy.sol"
      - "contracts/strategies/aave/earn/EarnAaveStrategy.sol"
      - "contracts/strategies/aave/earn/EarnAaveStrategyETH.sol"

jobs:
  veth-earn-aave:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running vETH-DAI with Aave
        run: npm test "test/veth/vesper-earn-aave.js"
