name: veETH-DAI with AlphaLend
on:
  pull_request:
    paths:
      - "test/veth/vesper-earn-alpha-lend.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/alpha/AlphaLendStrategy.sol"
      - "contracts/strategies/alpha/earn/EarnAlphaLendStrategy.sol"
      - "contracts/strategies/alpha/earn/EarnAlphaLendStrategyETH.sol"

jobs:
  veth-earn-alpha-lend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running vETH-DAI with AlphaLend
        run: npm test "test/veth/vesper-earn-alpha-lend.js"
