name: vUSDC with Curve a3Pool Avalanche
on:
  pull_request:
    paths:
      - "test/utils/setupHelper.js"
      - "test/vdai/crv-a3pool.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/curve/AaveCore.sol"
      - "contracts/strategies/curve/CrvBase.sol"
      - "contracts/strategies/curve/Crv3x.sol"
      - "contracts/strategies/curve/Crv3PoolStrategyBase.sol"
      - "contracts/strategies/curve/a3Pool/CrvA3PoolAvaxStrategy.sol"
      - "contracts/strategies/curve/a3Pool/CrvA3PoolStrategyBase.sol"

jobs:
  vdai-curveA3p-strategy-test:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/avalanche.env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running tests for vDAI with Curve 3Pool
        run: npm test "test/vusdc/crv-a3pool.js"