name: veWBTC-DAI with Compound
on:
  pull_request:
    paths:
      - "test/vwbtc/earn-compound.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/compound/CompoundStrategy.sol"
      - "contracts/strategies/compound/earn/EarnCompoundStrategy.sol"
      - "contracts/strategies/compound/earn/EarnCompoundStrategyWBTC.sol"

jobs:
  vwbtc-earn-compound:
    runs-on: ubuntu-latest
    env:
      NODE_URL: ${{ secrets.NODE_URL }}
    strategy:
      matrix:
        node: [14]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running veWBTC-DAI with Compound
        run: npm test "test/vwbtc/earn-compound.js"
