name: veWBTC-DAI with Curve sBTC
on:
  pull_request:
    paths:
      - "test/vwbtc/vesper-earn-crv-sWBTC.js"
      - "contracts/strategies/Strategy.sol"
      - "contracts/strategies/curve/CrvBase.sol"
      - "contracts/strategies/curve/Crv3x.sol"
      - "contracts/strategies/curve/Crv3PoolStrategyBase.sol"
      - "contracts/strategies/curve/3Pool/CrvsBTCPoolStrategy.sol"
      - "contracts/strategies/curve/3Pool/earn/EarnCrvsBTCStrategy.sol"

jobs:
  vwbtc-earn-curve:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          submodules: true
      - run: cat "${GITHUB_WORKSPACE}/.github/env.properties" >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Run npm install with node v${{ matrix.node }}
        run: npm install

      - name: Running vWBTC-DAI with Compound
        run: npm test "test/vwbtc/vesper-earn-crv-sWBTC.js"
